baseURL = 'http://danielzamo.github.io/'
languageCode = 'en-us'
title = 'Site'
theme = "hugo-theme-relearn"

[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]


[mediaTypes]
  [mediaTypes."text/javascript"]
    suffixes = ["js"]

[outputFormats]
  [outputFormats.PRINT]
    name= "PRINT"
    baseName = "index.print"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

  [outputFormats.SEARCH]
    name= "SEARCH"
    baseName = "index.search"
    isPlainText = true
    mediaType = 'text/javascript'
    permalinkable = false
    noUgly = true

  [outputFormats.SERCHPAGE]
    name= "SEARCHPAGE"
    baseName = "search"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

[params]
  alwaysopen = true
  editURL = ""
  author = "dzamo"
  description = ""
#  showVisitedLinks = false
#  disableSearch = false
#  disableSearchHiddenPages = false
#  disableSeoHiddenPages = false
#  disableTagHiddenPages = false
#  disableAssetsBusting = false
#  disableGeneratorVersion = false
#  disableInlineCopyToClipBoard = false
#  disableShortcutsTitle = false
  disableLandingPageButton = true
#  disableLanguageSwitchingButton = false
#  disableBreadcrumb = true
#  disableToc = false
#  disableMathJax = false
#  customMathJaxURL = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
#  mathJaxInitialize = "{}"
#  disableMermaid = false
#  customMermaidURL = "https://unpkg.com/mermaid/dist/mermaid.min.js"
  mermaidInitialize = "{ \"theme\": \"default\" }"
#  disableOpenapi = false
#  customOpenapiURL = "https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js"
#  disableNextPrev = true
#  ordersectionsby = "weight"
#  themeVariant = "auto"
  themeVariant = [ "relearn-dark","relearn-light"]
#  breadcrumbSeparator = "|"
#  titleSeparator = "-"
#  collapsibleMenu = false
#  additionalContentLanguage = [ "en" ]
#  disableExplicitIndexURLs = false
#  externalLinkTarget = "_blank"
#
